version: '3.8'
services:
  task-manager:
    build: .
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:8080"