CREATE TABLE app_users (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           email varchar(100) NOT NULL UNIQUE,
                           role varchar(20) NOT NULL,
                           login varchar(30) NOT NULL UNIQUE,
                           password varchar(100) NOT NULL,
                           created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tasks (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title varchar(100) NOT NULL,
                       description varchar(500) NOT NULL,
                       status varchar(20) NOT NULL,
                       priority varchar(20) NOT NULL,
                       owner_id int NOT NULL REFERENCES app_users(id),
                       performer_id int REFERENCES app_users(id),
                       created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at timestamp
);

CREATE TABLE comments (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          text varchar(1000) NOT NULL,
                          created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at timestamp,
                          user_id int NOT NULL REFERENCES app_users(id),
                          task_id int NOT NULL REFERENCES tasks(id) ON DELETE CASCADE
);

ALTER TABLE tasks ADD CONSTRAINT chk_status
    CHECK (status IN ('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'));


ALTER TABLE tasks ADD CONSTRAINT chk_priority
    CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'));


ALTER TABLE App_users ADD CONSTRAINT chk_role
    CHECK(role IN ('ADMIN', 'USER', 'MODERATOR'));

-- Для пользователей
CREATE INDEX idx_user_email ON app_users(email); -- Для входа по email
CREATE INDEX idx_user_role ON app_users(role); -- Если будет поиск по ролям

-- Для задач
CREATE INDEX idx_task_owner ON tasks(owner_id);
CREATE INDEX idx_task_performer ON tasks(performer_id);
CREATE INDEX idx_task_status ON tasks(status); -- Если часты фильтры по статусу

-- Для комментариев
CREATE INDEX idx_comment_task ON comments(task_id);
CREATE INDEX idx_comment_created ON comments(created_at); -- Для сортировки по дате

INSERT INTO app_users (email,role,login,password)VALUES ('admin@mail.com','ADMIN','test-admin','$2a$10$FC/ku1NoR8EUJ3xrU1.zxuMto2927qAHJkCX1SVEldwgIleFCMuyK');
INSERT INTO app_users (email,role,login,password)VALUES ('user@mail.com','USER','test-user','$2a$10$L1HWIksj3PwfJ/q2kcYMK.F.Gl7.oToQv11wlNq7EZn6A7f8u52Iu');
INSERT INTO app_users (email,role,login,password)VALUES ('moderator@mail.com','MODERATOR','test-moderator','$2a$10$QHL51KzlnjJEi4FM.OczA.6nVbNL7Po6Zruw3NkrXAaiKoxmLyKya');